module.exports = {
  apps: [
    {
      name: 'politimonitor',
      script: 'node_modules/.bin/next',
      args: 'start',
      cwd: '/root/JFN',
      instances: 2,
      exec_mode: 'cluster',
      max_memory_restart: '800M',
      env: {
        NODE_ENV: 'production',
        PORT: 3000,
      },
      error_file: '/var/log/politimonitor/err.log',
      out_file: '/var/log/politimonitor/out.log',
      log_date_format: 'YYYY-MM-DD HH:mm:ss',
      merge_logs: true,
      autorestart: true,
      watch: false,
      restart_delay: 3000,
    },
    {
      name: 'bond-worker',
      script: 'node_modules/.bin/tsx',
      args: 'src/agent/bond-worker.ts',
      cwd: '/root/JFN',
      instances: 1,
      exec_mode: 'fork',
      max_memory_restart: '400M',
      env: {
        NODE_ENV: 'production',
      },
      error_file: '/var/log/politimonitor/bond-err.log',
      out_file: '/var/log/politimonitor/bond-out.log',
      log_date_format: 'YYYY-MM-DD HH:mm:ss',
      autorestart: true,
      watch: false,
    },
    {
      name: 'hermes-worker',
      script: 'node_modules/.bin/tsx',
      args: 'src/agent/hermes-worker.ts',
      cwd: '/root/JFN',
      instances: 1,
      exec_mode: 'fork',
      max_memory_restart: '400M',
      env: {
        NODE_ENV: 'production',
      },
      error_file: '/var/log/politimonitor/hermes-err.log',
      out_file: '/var/log/politimonitor/hermes-out.log',
      log_date_format: 'YYYY-MM-DD HH:mm:ss',
      autorestart: true,
      watch: false,
    },
    {
      name: 'whatsapp-worker',
      script: 'node_modules/.bin/tsx',
      args: 'src/agent/whatsapp-worker.ts',
      cwd: '/root/JFN',
      instances: 1,
      exec_mode: 'fork',
      max_memory_restart: '400M',
      env: {
        NODE_ENV: 'production',
      },
      error_file: '/var/log/politimonitor/whatsapp-err.log',
      out_file: '/var/log/politimonitor/whatsapp-out.log',
      log_date_format: 'YYYY-MM-DD HH:mm:ss',
      autorestart: true,
      watch: false,
    },
  ],
}
